<wsdl:definitions
     name="EmpDBRef"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOAAppls/EmpDBSample/EmpDBRef"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOAAppls/EmpDBSample/EmpDBRef"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/EmpDBRef"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="EmpDBRef_plt" >
    <plt:role name="EmpDBRef_role" >
      <plt:portType name="tns:EmpDBRef_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/EmpDBRef" schemaLocation="../Schemas/EmpDBRef_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="EmpDBRefSelect_inputParameters">
        <wsdl:part name="EmpDBRefSelect_inputParameters" element="top:EmpDBRefSelect_deptIdInputParameters"/>
    </wsdl:message>
    <wsdl:message name="EmployeesCollection_msg">
        <wsdl:part name="EmployeesCollection" element="top:EmployeesCollection"/>
    </wsdl:message>
    <wsdl:portType name="EmpDBRef_ptt">
        <wsdl:operation name="EmpDBRefSelect">
            <wsdl:input message="tns:EmpDBRefSelect_inputParameters"/>
            <wsdl:output message="tns:EmployeesCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
